version: "3.9"

services:
  node-express:
    build: .
    command: yarn dev:server
    restart: always
    env_file: .env
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017

    networks:
      - node-webapp-network

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - node-webapp-network

  mongo-express:
    container_name: mongo_admin
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=appserver
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123

    depends_on:
      - mongodb
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    name: appserver
    driver: bridge